[package]
name = "rules"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
b_2 = { path = "../../wsdl_rs/b_2" }
common = { path = "../common" }
onvif = { package = "onvif-xsd", path = "../../xsd_rs/onvif_xsd" }
soap_envelope = { path = "../../xsd_rs/soap_envelope" }
validate = { path = "../../validate" }
xml-rs = "0.8.3"
xmlmime = { path = "../../xsd_rs/xmlmime" }
xop = { path = "../../xsd_rs/xop" }
xsd-macro-utils = { git = "https://github.com/voysys/xsd-parser-rs", tag = "voysys-1" }
xsd-types = { git = "https://github.com/voysys/xsd-parser-rs", tag = "voysys-1" }
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
