[package]
name = "bf_2"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
validate = { path = "../../validate" }
xml-rs = "0.8.3"
xsd-macro-utils = { git = "https://github.com/voysys/xsd-parser-rs", tag = "voysys-1" }
xsd-types = { git = "https://github.com/voysys/xsd-parser-rs", tag = "voysys-1" }
yaserde = "0.7.1"
yaserde_derive = "0.7.1"
ws_addr = { path = "../../wsdl_rs/ws_addr" }
xml_xsd = { path = "../../wsdl_rs/xml_xsd" }
